### ISSUE TITLE
Version 4.10.0 of iOSDFULibrary doesn't compile

### ISSUE THREAD

**Issue by pmurphyjam** [nordicsemi/IOS-DFU-Library#417]
Latest version 4.10.0 doesn't compile in Swift 5
Instantiating it as a Podfile, and it won't compile in Xcode 12.4.

**Comment by philips77** [comment]
It works for me. What errors do you have? Please, provide any logs or screenshots.

**Comment by philips77** [comment]
Perhaps you had an issue with not specified architectures? I just released 4.10.1 which should have this fixed. Please try the new version.

**Comment by pmurphyjam** [comment]
Installed latest version 4.10.1 still has compile problems. All the problems are in ButtonlessDFU.swift did a clean and build problem is still there. Running Swift 5, Xcode 12.4, iOS 14.4.2
<img width="3058" alt="Screen Shot 2021-04-30 at 4 34 02 PM" src="https://user-images.githubusercontent.com/4195165/116763217-f21a4900-a9d1-11eb-859f-957f8c9202f0.png">

**Comment by pmurphyjam** [comment]
After reverting to 4.9.0 this is what I see:
<img width="3062" alt="Screen Shot 2021-04-30 at 4 59 48 PM" src="https://user-images.githubusercontent.com/4195165/116764314-95209200-a9d5-11eb-9d32-69681fcc828e.png">

**Comment by philips77** [comment]
Ok, I'll fix it in Monday. Can you update to xcode 12.5? I don't have this issue there.

**Comment by ToHiren** [comment]
older Version of Xcode create problem below 12

**Comment by philips77** [comment]
> older Version of Xcode create problem below 12

Is it the same issue?

**Comment by philips77** [comment]
Fixed in 4.10.2. Also, this time I tested it in Xcode 12.4 and seems to be working.
