### ISSUE TITLE
dyld: Library not loaded: @rpath/Zip.framework/Zip w/ Carthage

### ISSUE THREAD

**Issue by jakerockland** [nordicsemi/IOS-DFU-Library#78]
I believe that this was caused by #77

**Comment by mostafaberg** [comment]
Taking a look at that now, how do I reproduce it ?

**Comment by mostafaberg** [comment]
Cannot reproduce here so I'm not sure if it has something to do with your project's configuration ? can you reproduce on a new empty project ? this will rule out one issue at least.

**Comment by jakerockland** [comment]
Definitely can reproduce with an empty project. Here is a dummy project that shows the issue.

[HelloWorld.zip](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/files/717417/HelloWorld.zip)

**Comment by jakerockland** [comment]
#77 removed the `Zip` dependency, preventing it from being build as an additional framework for Carthage users 😢

**Comment by mostafaberg** [comment]
@jakerockland Of course !, how silly of me, so sorry for that mistake, i seem to have forgotten to share the Zip scheme so it won't be build by Carthage , working on fix now :)

**Comment by mostafaberg** [comment]
Issue resolved in `3.0.6` by making the Zip framework scheme shared. now carthage picks it up and builds both iOSDFULibrary and Zip frameworks!

give it a shot and let me know if you experience any more issues!

**Comment by jakerockland** [comment]
I'm still seeing the same problem, same `dyld: Library not loaded: @rpath/Zip.framework/Zip` runtime crash with `3.0.6` using the same example project I had included above.

**Comment by jakerockland** [comment]
😱 😅

**Comment by jakerockland** [comment]
Whoops, that was actually an error on my end-- `3.0.6` is working now for me! Thank you @mostafaberg 😅 😄
